export type ToolKind = 'math' | 'code_executor' | 'web_search' | 'wiki' | 'bing_search';

export interface ToolDefinition {
  id: ToolKind;
  name: string;
  description: string;
  icon: string;
  comingSoon?: boolean;
  category: string;
  provider: string;
  integration: string;
  capabilities: string[];
  requirements: string;
  bestFor: string;
  tags: string[];
  version: string;
}

export const TOOL_REGISTRY: ToolDefinition[] = [
  {
    id: 'math',
    name: 'Math Calculator',
    description: 'Execute numeric calculations and evaluate expressions.',
    icon: '🧮',
    category: 'Research & Knowledge',
    provider: 'System Runtime',
    integration: 'SDK hook · JSON payload',
    capabilities: [
      'Supports arithmetic and algebraic operations',
      'Handles equations and expression evaluation',
      'Returns precise numeric outputs'
    ],
    requirements: 'Included with workspace',
    bestFor: 'Agents that need deterministic calculations',
    tags: ['math', 'calculation', 'utility'],
    version: '1.0'
  },
  {
    id: 'code_executor',
    name: 'Code Executor',
    description: 'Run Python snippets and return their output.',
    icon: '💻',
    category: 'Execution & Sandbox',
    provider: 'Secure Sandbox',
    integration: 'gRPC microservice · Streaming logs',
    capabilities: [
      'Executes Python 3.11 code in isolation',
      'Streams stdout/stderr output',
      'Captures artifacts generated by the run'
    ],
    requirements: 'Execution credits per minute',
    bestFor: 'Evaluation, testing, automation workflows',
    tags: ['code', 'runtime', 'python'],
    version: '1.1'
  },
  {
    id: 'wiki',
    name: 'Wiki Explorer',
    description: 'Retrieve structured Wikipedia summaries and related article links.',
    icon: '📚',
    category: 'Research & Knowledge',
    provider: 'Wikipedia API',
    integration: 'REST API · JSON extracts',
    capabilities: [
      'Fetches concise article summaries and metadata',
      'Surfaces related topics and cross-language links',
      'Supports disambiguation handling for ambiguous terms'
    ],
    requirements: 'Public API access (no key required)',
    bestFor: 'Quick fact-checking and background research',
    tags: ['wiki', 'knowledge base', 'reference'],
    version: '1.0'
  },
  {
    id: 'bing_search',
    name: 'Bing Search',
    description: 'Enterprise-grade search across web, images, news, and videos.',
    icon: '🔍',
    category: 'Research & Knowledge',
    provider: 'Microsoft Bing',
    integration: 'REST API · JSON result bundles',
    capabilities: [
      'Multi-vertical search (web, news, images, video)',
      'Result enrichment with ranking signals and snippets',
      'Supports market, language, and freshness tuning'
    ],
    requirements: 'Azure Cognitive Services key',
    bestFor: 'Monitoring, competitive intelligence, multimedia discovery',
    tags: ['search', 'bing', 'news'],
    version: '1.0'
  }
];

export const getToolById = (id: ToolKind): ToolDefinition | undefined =>
  TOOL_REGISTRY.find(tool => tool.id === id);

export const TOOL_OPTIONS = TOOL_REGISTRY.map(tool => ({
  value: tool.id,
  label: tool.name,
  description: tool.description,
  icon: tool.icon,
  comingSoon: tool.comingSoon ?? false
}));
